# Generated by Django 3.1.2 on 2020-11-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreasBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/img.png', upload_to='areaBrands')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/img.png', upload_to='brands')),
            ],
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/img.png', upload_to='methods')),
                ('areaBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.areasbrands')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('shortDescription', models.CharField(max_length=120)),
                ('importance', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/img.png', upload_to='products')),
                ('code', models.IntegerField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.methods')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/img.png', upload_to='images')),
                ('mobile', models.BooleanField(default=False)),
                ('importance', models.IntegerField()),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.news')),
            ],
        ),
        migrations.AddField(
            model_name='areasbrands',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.brands'),
        ),
    ]
