# Generated by Django 3.1.2 on 2020-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_areas_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
