# Generated by Django 3.1.2 on 2020-11-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_areas_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasbrands',
            name='image',
            field=models.ImageField(default='default/img.png', upload_to='non-static/areaBrands'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(default='default/img.png', upload_to='non-static/brands'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='default/img.png', upload_to='non-static/images'),
        ),
        migrations.AlterField(
            model_name='methods',
            name='image',
            field=models.ImageField(default='default/img.png', upload_to='non-static/methods'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default/img.png', upload_to='non-static/products'),
        ),
    ]
