# Generated by Django 3.1.2 on 2020-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201111_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.TextField(),
        ),
    ]
