# Generated by Django 3.1.2 on 2020-11-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201117_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='importance',
            new_name='index',
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.images'),
        ),
    ]
