# Generated by Django 3.1.2 on 2020-11-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20201117_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.images', unique=True),
        ),
    ]
