# Generated by Django 3.1.2 on 2020-11-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20201117_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, default=None, null=True)),
                ('mobile', models.BooleanField(default=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.images')),
            ],
        ),
        migrations.DeleteModel(
            name='Mobiles',
        ),
    ]
