# Generated by Django 3.1.2 on 2020-11-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20201119_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='x',
            new_name='point',
        ),
    ]
