# Generated by Django 3.1.2 on 2020-11-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20201119_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='mobile',
        ),
    ]
